### PR TITLE
fix #4527 by considering request URL protocol instead of request schema

### LINKED ISSUE #4527: ExternalContextImpl.encodeWebsocketURL fails behind SSL termination
Hi

I'm using `<f:websocket>` and do get JS error:

```
jsf.js:1 Mixed Content: The page at 'https://...' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://.../javax.faces.push/events?ea1d8743-eca9-45a0-b548-ad3b1fd48c69'. This request has been blocked; this endpoint must be available over WSS.
```

`ExternalContextImpl` uses [`request.getSchema()`](https://github.com/eclipse-ee4j/mojarra/blob/2ba2a3b5dfd339745a7adba6f5ca77100d97dc68/impl/src/main/java/com/sun/faces/context/ExternalContextImpl.java#L669) to determine the correct protocol, yet that does not work behind a reverse proxy terminating SSL (HTTPS) and forwarding the request via HTTP.

Instead, it should use [`HttpServletRequest#getRequestURL()`](https://javaee.github.io/javaee-spec/javadocs/javax/servlet/http/HttpServletRequest.html#getRequestURL--).

### PR DESCRIPTION
**Pull request by schulzp**

### CODE REVIEW

File: impl/src/test/java/com/sun/faces/context/ExternalContextImplWebsocketTest.java [hunk 1]
```diff
@@ -0,0 +1,75 @@
+package com.sun.faces.context;
```
Comment (arjantijms) [inline impl/src/test/java/com/sun/faces/context/ExternalContextImplWebsocketTest.java]: Looks good, but needs a license header (you can copy the EPL header from another file and then add your own name)

Comment (schulzp) [reply impl/src/test/java/com/sun/faces/context/ExternalContextImplWebsocketTest.java]: @arjantijms, done, added the license header

**Comment by arjantijms** [comment]
@schulzp I think we're ready to merge this now ;) Thx for your contribution!
