### PR TITLE
Fix Exception in HtmlResponseWriter

### LINKED ISSUE #4650: ArrayIndexOutOfBoundsException with index -2 in HtmlResponseWriter.writeUnescapedCData(...)
Placing an EL expression that returns an empty String in a script element (and most certainly anywhere as CDATA) leads to an ArrayIndexOutOfBoundsException with index -2 in
HtmlResponseWriter.writeUnescapedCData(...).
The case of an empty String is simply uncovered in the method.

### PR DESCRIPTION
**Pull request by OBreidenbach**
fix #4650

### CODE REVIEW

**Comment by tandraschko** [comment]
+1
@arjantijms any chance for a Bugfix Version soon? There are really good bugfix PRs here

**Comment by cmunier** [comment]
Hi,
@arjantijms Can you please consider this for an upcoming patch release?
https://github.com/eclipse-ee4j/mojarra/issues/4647 / https://github.com/eclipse-ee4j/mojarra/issues/4650 is a severe issue to us with no effective workaround.
Thanks!

File: impl/src/test/java/com/sun/faces/renderkit/html_basic/HtmlResponseWriterTest.java [hunk 1]
```diff
@@ -155,6 +155,9 @@ public void testUnescapedCDATA() throws Exception {
         HtmlResponseWriter responseWriter = new HtmlResponseWriter(stringWriter, "application/xhtml+xml", "UTF-8");
         responseWriter.startElement("style", null);
         responseWriter.startCDATA();
+        // make sure empty string is handle correct
```
Comment (manorrock) [inline impl/src/test/java/com/sun/faces/renderkit/html_basic/HtmlResponseWriterTest.java:158]: Please copy the entire test method instead of adding this comment and name it testUnescapedCDataWithZeroLengthContent

Comment (OBreidenbach) [reply impl/src/test/java/com/sun/faces/renderkit/html_basic/HtmlResponseWriterTest.java]: I changed the test method as requested. 
Sorry for removing the withspaces. My IDE did this and I didnot pay attention.

**Review by manorrock — APPROVED** [review]

**Comment by manorrock** [comment]
@arjantijms or @BalusC Can you please review. Once either of you approve we can merge this. Thanks!

**Review by arjantijms — APPROVED** [review]

**Comment by erickdeoliveiraleal** [comment]
@BalusC please merge it to 2.3 branch too

**Comment by BalusC** [comment]
That was already done via https://github.com/eclipse-ee4j/mojarra/issues/4647
