### PR TITLE
Fix #5511: don't anymore rely on CodeSource#getLocation()

### LINKED ISSUE #5511: Deployment of JF Web Application fails on Tomcat 11 but works on Tomcat 10
For reproduction I have created a trivial/minimal jf web application [example.zip](https://github.com/user-attachments/files/17341628/example.zip), which simpliy prints Hello World and does not even use one line of Java-Code. Imho any other JF web app would also would be ok. Simply rename the file from `example.zip` to `example.war` (GitHub likes no war attachements to this report) and put it into the deploy folder `webapps` of a fresh unzipped Tomcat 11.0.0 download. Then start it via `bin/startup.bat/sh` . Unfortunately, the app is not loaded and the server's log and the content shown in the browser (at the URL of the not loaded webapp) looks similar to the following:

```text
Okt. 11, 2024 12:23:05 PM org.apache.catalina.startup.VersionLoggerListener log
INFORMATION: Server Version:        Apache Tomcat/11.0.0
Okt. 11, 2024 12:23:05 PM org.apache.catalina.startup.VersionLoggerListener log
INFORMATION: Server built:          Oct 3 2024 17:00:16 UTC
Okt. 11, 2024 12:23:05 PM org.apache.catalina.startup.VersionLoggerListener log
INFORMATION: Server version number: 11.0.0.0
Okt. 11, 2024 12:23:05 PM org.apache.catalina.startup.VersionLoggerListener log
INFORMATION: OS Name:               Windows 11
Okt. 11, 2024 12:23:05 PM org.apache.catalina.startup.VersionLoggerListener log
INFORMATION: OS Version:            10.0
Okt. 11, 2024 12:23:05 PM org.apache.catalina.startup.VersionLoggerListener log
INFORMATION: Architektur:           amd64
Okt. 11, 2024 12:23:05 PM org.apache.catalina.startup.VersionLoggerListener log
INFORMATION: Java Home:             C:\Program Files\Java\jdk-22.0.2
Okt. 11, 2024 12:23:05 PM org.apache.catalina.startup.VersionLoggerListener log
INFORMATION: JVM Version:           22.0.2+9-70
Okt. 11, 2024 12:23:05 PM org.apache.catalina.startup.VersionLoggerListener log
INFORMATION: JVM Hersteller:        Oracle Corporation
Okt. 11, 2024 12:23:05 PM org.apache.catalina.startup.VersionLoggerListener log
INFORMATION: CATALINA_BASE:         C:\source\.metadata\.plugins\org.eclipse.wst.server.core\tmp0
Okt. 11, 2024 12:23:05 PM org.apache.catalina.startup.VersionLoggerListener log
INFORMATION: CATALINA_HOME:         C:\Program Files\Tomcat
Okt. 11, 2024 12:23:05 PM org.apache.catalina.startup.VersionLoggerListener log
INFORMATION: Command line argument: -Dcatalina.base=C:\source\.metadata\.plugins\org.eclipse.wst.server.core\tmp0
Okt. 11, 2024 12:23:05 PM org.apache.catalina.startup.VersionLoggerListener log
INFORMATION: Command line argument: -Dcatalina.home=C:\Program Files\Tomcat
Okt. 11, 2024 12:23:05 PM org.apache.catalina.startup.VersionLoggerListener log
INFORMATION: Command line argument: -Dwtp.deploy=C:\source\.metadata\.plugins\org.eclipse.wst.server.core\tmp0\wtpwebapps
Okt. 11, 2024 12:23:05 PM org.apache.catalina.startup.VersionLoggerListener log
INFORMATION: Command line argument: --add-opens=java.base/java.lang=ALL-UNNAMED
Okt. 11, 2024 12:23:05 PM org.apache.catalina.startup.VersionLoggerListener log
INFORMATION: Command line argument: --add-opens=java.base/java.io=ALL-UNNAMED
Okt. 11, 2024 12:23:05 PM org.apache.catalina.startup.VersionLoggerListener log
INFORMATION: Command line argument: --add-opens=java.base/java.util=ALL-UNNAMED
Okt. 11, 2024 12:23:05 PM org.apache.catalina.startup.VersionLoggerListener log
INFORMATION: Command line argument: --add-opens=java.base/java.util.concurrent=ALL-UNNAMED
Okt. 11, 2024 12:23:05 PM org.apache.catalina.startup.VersionLoggerListener log
INFORMATION: Command line argument: --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
Okt. 11, 2024 12:23:05 PM org.apache.catalina.startup.VersionLoggerListener log
INFORMATION: Command line argument: -Djava.library.path=C:\Program Files\Tomcat\bin
Okt. 11, 2024 12:23:05 PM org.apache.catalina.startup.VersionLoggerListener log
INFORMATION: Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
Okt. 11, 2024 12:23:05 PM org.apache.catalina.startup.VersionLoggerListener log
INFORMATION: Command line argument: -ea
Okt. 11, 2024 12:23:05 PM org.apache.catalina.startup.VersionLoggerListener log
INFORMATION: Command line argument: -Dfile.encoding=UTF-8
Okt. 11, 2024 12:23:05 PM org.apache.catalina.startup.VersionLoggerListener log
INFORMATION: Command line argument: -Dstdout.encoding=UTF-8
Okt. 11, 2024 12:23:05 PM org.apache.catalina.startup.VersionLoggerListener log
INFORMATION: Command line argument: -Dstderr.encoding=UTF-8
Okt. 11, 2024 12:23:05 PM org.apache.catalina.startup.VersionLoggerListener log
INFORMATION: Command line argument: -XX:+ShowCodeDetailsInExceptionMessages
Okt. 11, 2024 12:23:05 PM org.apache.catalina.core.AprLifecycleListener lifecycleEvent
INFORMATION: Loaded Apache Tomcat Native library [2.0.8] using APR version [1.7.4].
Okt. 11, 2024 12:23:05 PM org.apache.catalina.core.AprLifecycleListener initializeSSL
INFORMATION: OpenSSL successfully initialized [OpenSSL 3.0.14 4 Jun 2024]
Okt. 11, 2024 12:23:06 PM org.apache.coyote.AbstractProtocol init
INFORMATION: Initialisiere ProtocolHandler["http-nio-80"]
Okt. 11, 2024 12:23:06 PM org.apache.coyote.AbstractProtocol init
INFORMATION: Initialisiere ProtocolHandler["https-openssl-nio2-443"]
Okt. 11, 2024 12:23:06 PM org.apache.tomcat.util.net.AbstractEndpoint logCertificate
INFORMATION: Connector [https-openssl-nio2-443], TLS virtual host [_default_], certificate type [RSA] configured from key [C:\Program Files\Tomcat/conf/ssl/server.key], certificate [C:\Program Files\Tomcat/conf/ssl/server.crt] and certificate chain [C:\Program Files\Tomcat/conf/ssl/ca.crt] with trust store [null]
Okt. 11, 2024 12:23:06 PM org.apache.catalina.startup.Catalina load
INFORMATION: Server initialization in [642] milliseconds
Okt. 11, 2024 12:23:06 PM org.apache.catalina.core.StandardService startInternal
INFORMATION: Starting service [Catalina]
Okt. 11, 2024 12:23:06 PM org.apache.catalina.core.StandardEngine startInternal
INFORMATION: Starting Servlet engine: [Apache Tomcat/11.0.0]
Okt. 11, 2024 12:23:07 PM org.apache.jasper.servlet.TldScanner scanJars
INFORMATION: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
Okt. 11, 2024 12:23:07 PM org.jboss.weld.environment.servlet.EnhancedListener onStartup
INFO: WELD-ENV-001008: Initialize Weld using ServletContainerInitializer
Okt. 11, 2024 12:23:07 PM org.jboss.weld.bootstrap.WeldStartup <clinit>
INFO: WELD-000900: 5.1.3 (Final)
Okt. 11, 2024 12:23:07 PM org.jboss.weld.environment.deployment.discovery.ReflectionDiscoveryStrategy processAnnotatedDiscovery
INFO: WELD-ENV-000014: Falling back to Java Reflection for bean-discovery-mode="annotated" discovery. Add org.jboss:jandex to the classpath to speed-up startup.
Okt. 11, 2024 12:23:07 PM org.jboss.weld.bootstrap.WeldStartup startContainer
INFO: WELD-000101: Transactional services not available. Injection of @Inject UserTransaction not available. Transactional observers will be invoked synchronously.
Okt. 11, 2024 12:23:07 PM org.jboss.weld.environment.tomcat.TomcatContainer initialize
INFO: WELD-ENV-001100: Tomcat 7+ detected, CDI injection will be available in Servlets, Filters and Listeners.
Okt. 11, 2024 12:23:07 PM com.sun.faces.config.ConfigureListener contextInitialized
INFORMATION: Mojarra 4.0.7 für Kontext '/example' wird initialisiert.
Okt. 11, 2024 12:23:08 PM com.sun.faces.spi.InjectionProviderFactory createInstance
INFORMATION: JSF1048: PostConstruct/PreDestroy-Annotationen vorhanden.  Verwaltete Bean-Methoden, die mit diesen Annotationen markiert sind, lassen die entsprechenden Annotationen verarbeiten.
jakarta.faces.FacesException: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "java.net.URL.toString()" because the return value of "java.security.CodeSource.getLocation()" is null
	at com.sun.faces.config.ConfigManager.getAnnotatedClasses(ConfigManager.java:204)
	at com.sun.faces.config.processor.AbstractConfigProcessor.processAnnotations(AbstractConfigProcessor.java:303)
	at com.sun.faces.config.processor.ApplicationConfigProcessor.process(ApplicationConfigProcessor.java:308)
	at com.sun.faces.config.ConfigManager.lambda$initialize$0(ConfigManager.java:265)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:722)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:782)
	at com.sun.faces.config.ConfigManager.initialize(ConfigManager.java:263)
	at com.sun.faces.config.ConfigureListener.contextInitialized(ConfigureListener.java:185)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:3964)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4390)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:164)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1170)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1160)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:716)
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:771)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:164)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1170)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1160)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:716)
	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:203)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:164)
	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:415)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:164)
	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:866)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:164)
	at org.apache.catalina.startup.Catalina.start(Catalina.java:755)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:342)
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:470)
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "java.net.URL.toString()" because the return value of "java.security.CodeSource.getLocation()" is null
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at com.sun.faces.config.ConfigManager.getAnnotatedClasses(ConfigManager.java:202)
	... 35 more
Caused by: java.lang.NullPointerException: Cannot invoke "java.net.URL.toString()" because the return value of "java.security.CodeSource.getLocation()" is null
	at com.sun.faces.config.manager.tasks.ProvideMetadataToAnnotationScanTask.initializeIvars(ProvideMetadataToAnnotationScanTask.java:78)
	at com.sun.faces.config.manager.tasks.ProvideMetadataToAnnotationScanTask.getAnnotationScanURIs(ProvideMetadataToAnnotationScanTask.java:91)
	at com.sun.faces.config.manager.tasks.FindAnnotatedConfigClasses.call(FindAnnotatedConfigClasses.java:83)
	at com.sun.faces.config.manager.tasks.FindAnnotatedConfigClasses.call(FindAnnotatedConfigClasses.java:40)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at com.sun.faces.config.ConfigManager.findAnnotations(ConfigManager.java:357)
	at com.sun.faces.config.ConfigManager.initialize(ConfigManager.java:250)
	... 29 more
jakarta.faces.FacesException: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "java.net.URL.toString()" because the return value of "java.security.CodeSource.getLocation()" is null
	at com.sun.faces.config.ConfigManager.getAnnotatedClasses(ConfigManager.java:204)
	at com.sun.faces.config.processor.AbstractConfigProcessor.processAnnotations(AbstractConfigProcessor.java:303)
	at com.sun.faces.config.processor.ComponentConfigProcessor.process(ComponentConfigProcessor.java:79)
	at com.sun.faces.config.ConfigManager.lambda$initialize$1(ConfigManager.java:295)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:722)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:782)
	at com.sun.faces.config.ConfigManager.initialize(ConfigManager.java:278)
	at com.sun.faces.config.ConfigureListener.contextInitialized(ConfigureListener.java:185)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:3964)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4390)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:164)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1170)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1160)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:716)
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:771)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:164)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1170)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1160)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:716)
	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:203)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:164)
	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:415)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:164)
	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:866)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:164)
	at org.apache.catalina.startup.Catalina.start(Catalina.java:755)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:342)
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:470)
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "java.net.URL.toString()" because the return value of "java.security.CodeSource.getLocation()" is null
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at com.sun.faces.config.ConfigManager.getAnnotatedClasses(ConfigManager.java:202)
	... 35 more
Caused by: java.lang.NullPointerException: Cannot invoke "java.net.URL.toString()" because the return value of "java.security.CodeSource.getLocation()" is null
	at com.sun.faces.config.manager.tasks.ProvideMetadataToAnnotationScanTask.initializeIvars(ProvideMetadataToAnnotationScanTask.java:78)
	at com.sun.faces.config.manager.tasks.ProvideMetadataToAnnotationScanTask.getAnnotationScanURIs(ProvideMetadataToAnnotationScanTask.java:91)
	at com.sun.faces.config.manager.tasks.FindAnnotatedConfigClasses.call(FindAnnotatedConfigClasses.java:83)
	at com.sun.faces.config.manager.tasks.FindAnnotatedConfigClasses.call(FindAnnotatedConfigClasses.java:40)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at com.sun.faces.config.ConfigManager.findAnnotations(ConfigManager.java:357)
	at com.sun.faces.config.ConfigManager.initialize(ConfigManager.java:250)
	... 29 more
jakarta.faces.FacesException: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "java.net.URL.toString()" because the return value of "java.security.CodeSource.getLocation()" is null
	at com.sun.faces.config.ConfigManager.getAnnotatedClasses(ConfigManager.java:204)
	at com.sun.faces.config.processor.AbstractConfigProcessor.processAnnotations(AbstractConfigProcessor.java:303)
	at com.sun.faces.config.processor.ConverterConfigProcessor.process(ConverterConfigProcessor.java:77)
	at com.sun.faces.config.ConfigManager.lambda$initialize$1(ConfigManager.java:295)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:722)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:782)
	at com.sun.faces.config.ConfigManager.initialize(ConfigManager.java:278)
	at com.sun.faces.config.ConfigureListener.contextInitialized(ConfigureListener.java:185)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:3964)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4390)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:164)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1170)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1160)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:716)
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:771)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:164)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1170)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1160)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:716)
	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:203)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:164)
	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:415)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:164)
	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:866)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:164)
	at org.apache.catalina.startup.Catalina.start(Catalina.java:755)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:342)
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:470)
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "java.net.URL.toString()" because the return value of "java.security.CodeSource.getLocation()" is null
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at com.sun.faces.config.ConfigManager.getAnnotatedClasses(ConfigManager.java:202)
	... 35 more
Caused by: java.lang.NullPointerException: Cannot invoke "java.net.URL.toString()" because the return value of "java.security.CodeSource.getLocation()" is null
	at com.sun.faces.config.manager.tasks.ProvideMetadataToAnnotationScanTask.initializeIvars(ProvideMetadataToAnnotationScanTask.java:78)
	at com.sun.faces.config.manager.tasks.ProvideMetadataToAnnotationScanTask.getAnnotationScanURIs(ProvideMetadataToAnnotationScanTask.java:91)
	at com.sun.faces.config.manager.tasks.FindAnnotatedConfigClasses.call(FindAnnotatedConfigClasses.java:83)
	at com.sun.faces.config.manager.tasks.FindAnnotatedConfigClasses.call(FindAnnotatedConfigClasses.java:40)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at com.sun.faces.config.ConfigManager.findAnnotations(ConfigManager.java:357)
	at com.sun.faces.config.ConfigManager.initialize(ConfigManager.java:250)
	... 29 more
jakarta.faces.FacesException: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "java.net.URL.toString()" because the return value of "java.security.CodeSource.getLocation()" is null
	at com.sun.faces.config.ConfigManager.getAnnotatedClasses(ConfigManager.java:204)
	at com.sun.faces.config.processor.AbstractConfigProcessor.processAnnotations(AbstractConfigProcessor.java:303)
	at com.sun.faces.config.processor.ValidatorConfigProcessor.process(ValidatorConfigProcessor.java:82)
	at com.sun.faces.config.ConfigManager.lambda$initialize$1(ConfigManager.java:295)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:722)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:782)
	at com.sun.faces.config.ConfigManager.initialize(ConfigManager.java:278)
	at com.sun.faces.config.ConfigureListener.contextInitialized(ConfigureListener.java:185)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:3964)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4390)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:164)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1170)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1160)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:716)
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:771)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:164)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1170)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1160)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:716)
	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:203)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:164)
	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:415)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:164)
	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:866)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:164)
	at org.apache.catalina.startup.Catalina.start(Catalina.java:755)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:342)
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:470)
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "java.net.URL.toString()" because the return value of "java.security.CodeSource.getLocation()" is null
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at com.sun.faces.config.ConfigManager.getAnnotatedClasses(ConfigManager.java:202)
	... 35 more
Caused by: java.lang.NullPointerException: Cannot invoke "java.net.URL.toString()" because the return value of "java.security.CodeSource.getLocation()" is null
	at com.sun.faces.config.manager.tasks.ProvideMetadataToAnnotationScanTask.initializeIvars(ProvideMetadataToAnnotationScanTask.java:78)
	at com.sun.faces.config.manager.tasks.ProvideMetadataToAnnotationScanTask.getAnnotationScanURIs(ProvideMetadataToAnnotationScanTask.java:91)
	at com.sun.faces.config.manager.tasks.FindAnnotatedConfigClasses.call(FindAnnotatedConfigClasses.java:83)
	at com.sun.faces.config.manager.tasks.FindAnnotatedConfigClasses.call(FindAnnotatedConfigClasses.java:40)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at com.sun.faces.config.ConfigManager.findAnnotations(ConfigManager.java:357)
	at com.sun.faces.config.ConfigManager.initialize(ConfigManager.java:250)
	... 29 more
jakarta.faces.FacesException: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "java.net.URL.toString()" because the return value of "java.security.CodeSource.getLocation()" is null
	at com.sun.faces.config.ConfigManager.getAnnotatedClasses(ConfigManager.java:204)
	at com.sun.faces.config.processor.AbstractConfigProcessor.processAnnotations(AbstractConfigProcessor.java:303)
	at com.sun.faces.config.processor.RenderKitConfigProcessor.process(RenderKitConfigProcessor.java:151)
	at com.sun.faces.config.ConfigManager.lambda$initialize$1(ConfigManager.java:295)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:722)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:782)
	at com.sun.faces.config.ConfigManager.initialize(ConfigManager.java:278)
	at com.sun.faces.config.ConfigureListener.contextInitialized(ConfigureListener.java:185)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:3964)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4390)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:164)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1170)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1160)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:716)
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:771)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:164)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1170)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1160)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:716)
	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:203)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:164)
	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:415)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:164)
	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:866)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:164)
	at org.apache.catalina.startup.Catalina.start(Catalina.java:755)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:342)
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:470)
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "java.net.URL.toString()" because the return value of "java.security.CodeSource.getLocation()" is null
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at com.sun.faces.config.ConfigManager.getAnnotatedClasses(ConfigManager.java:202)
	... 35 more
Caused by: java.lang.NullPointerException: Cannot invoke "java.net.URL.toString()" because the return value of "java.security.CodeSource.getLocation()" is null
	at com.sun.faces.config.manager.tasks.ProvideMetadataToAnnotationScanTask.initializeIvars(ProvideMetadataToAnnotationScanTask.java:78)
	at com.sun.faces.config.manager.tasks.ProvideMetadataToAnnotationScanTask.getAnnotationScanURIs(ProvideMetadataToAnnotationScanTask.java:91)
	at com.sun.faces.config.manager.tasks.FindAnnotatedConfigClasses.call(FindAnnotatedConfigClasses.java:83)
	at com.sun.faces.config.manager.tasks.FindAnnotatedConfigClasses.call(FindAnnotatedConfigClasses.java:40)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at com.sun.faces.config.ConfigManager.findAnnotations(ConfigManager.java:357)
	at com.sun.faces.config.ConfigManager.initialize(ConfigManager.java:250)
	... 29 more
jakarta.faces.FacesException: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "java.net.URL.toString()" because the return value of "java.security.CodeSource.getLocation()" is null
	at com.sun.faces.config.ConfigManager.getAnnotatedClasses(ConfigManager.java:204)
	at com.sun.faces.config.processor.AbstractConfigProcessor.processAnnotations(AbstractConfigProcessor.java:303)
	at com.sun.faces.config.processor.BehaviorConfigProcessor.process(BehaviorConfigProcessor.java:79)
	at com.sun.faces.config.ConfigManager.lambda$initialize$1(ConfigManager.java:295)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:722)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:782)
	at com.sun.faces.config.ConfigManager.initialize(ConfigManager.java:278)
	at com.sun.faces.config.ConfigureListener.contextInitialized(ConfigureListener.java:185)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:3964)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4390)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:164)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1170)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1160)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:716)
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:771)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:164)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1170)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1160)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:716)
	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:203)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:164)
	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:415)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:164)
	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:866)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:164)
	at org.apache.catalina.startup.Catalina.start(Catalina.java:755)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:342)
	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:470)
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "java.net.URL.toString()" because the return value of "java.security.CodeSource.getLocation()" is null
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at com.sun.faces.config.ConfigManager.getAnnotatedClasses(ConfigManager.java:202)
	... 35 more
Caused by: java.lang.NullPointerException: Cannot invoke "java.net.URL.toString()" because the return value of "java.security.CodeSource.getLocation()" is null
	at com.sun.faces.config.manager.tasks.ProvideMetadataToAnnotationScanTask.initializeIvars(ProvideMetadataToAnnotationScanTask.java:78)
	at com.sun.faces.config.manager.tasks.ProvideMetadataToAnnotationScanTask.getAnnotationScanURIs(ProvideMetadataToAnnotationScanTask.java:91)
	at com.sun.faces.config.manager.tasks.FindAnnotatedConfigClasses.call(FindAnnotatedConfigClasses.java:83)
	at com.sun.faces.config.manager.tasks.FindAnnotatedConfigClasses.call(FindAnnotatedConfigClasses.java:40)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at com.sun.faces.config.ConfigManager.findAnnotations(ConfigManager.java:357)
	at com.sun.faces.config.ConfigManager.initialize(ConfigManager.java:250)
	... 29 more
Okt. 11, 2024 12:23:08 PM org.apache.coyote.AbstractProtocol start
INFORMATION: Starting ProtocolHandler ["http-nio-80"]
Okt. 11, 2024 12:23:08 PM org.apache.coyote.AbstractProtocol start
INFORMATION: Starting ProtocolHandler ["https-openssl-nio2-443"]
Okt. 11, 2024 12:23:08 PM org.apache.catalina.startup.Catalina start
INFORMATION: Server startup in [2082] milliseconds
Okt. 11, 2024 12:23:09 PM com.sun.faces.util.Util notNullNamedObject
SCHWERWIEGEND: JSF1068: Komponente mit Komponententyp jakarta.faces.ViewRoot kann nicht instanziiert werden.
Okt. 11, 2024 12:23:09 PM com.sun.faces.util.Util notNullNamedObject
SCHWERWIEGEND: JSF1068: Komponente mit Komponententyp jakarta.faces.ViewRoot kann nicht instanziiert werden.
Okt. 11, 2024 12:23:09 PM org.apache.catalina.core.StandardWrapperValve invoke
SCHWERWIEGEND: Servlet.service() for servlet [facesServlet] in context with path [/example] threw exception [Ausdrucksfehler: Benanntes Objekt jakarta.faces.ViewRoot nicht gefunden.] with root cause
jakarta.faces.FacesException: Ausdrucksfehler: Benanntes Objekt jakarta.faces.ViewRoot nicht gefunden.
	at com.sun.faces.util.Util.notNullNamedObject(Util.java:518)
	at com.sun.faces.application.applicationimpl.InstanceFactory.createComponentApplyAnnotations(InstanceFactory.java:693)
	at com.sun.faces.application.applicationimpl.InstanceFactory.createComponent(InstanceFactory.java:195)
	at com.sun.faces.application.ApplicationImpl.createComponent(ApplicationImpl.java:415)
	at jakarta.faces.application.ApplicationWrapper.createComponent(ApplicationWrapper.java:291)
	at com.sun.faces.util.Util.getNamingContainerPrefix(Util.java:1254)
	at com.sun.faces.context.RequestParameterMap.getNamingContainerPrefix(RequestParameterMap.java:86)
	at com.sun.faces.context.RequestParameterMap.get(RequestParameterMap.java:56)
	at com.sun.faces.context.RequestParameterMap.get(RequestParameterMap.java:33)
	at java.base/java.util.Collections$UnmodifiableMap.get(Collections.java:1657)
	at com.sun.faces.context.PartialViewContextImpl.isAjaxRequest(PartialViewContextImpl.java:112)
	at com.sun.faces.context.AjaxNoAjaxExceptionHandler.getWrapped(AjaxNoAjaxExceptionHandler.java:35)
	at jakarta.faces.context.ExceptionHandlerWrapper.isListenerForSource(ExceptionHandlerWrapper.java:108)
	at com.sun.faces.application.applicationimpl.Events.processListeners(Events.java:236)
	at com.sun.faces.application.applicationimpl.Events.invokeComponentListenersFor(Events.java:177)
	at com.sun.faces.application.applicationimpl.Events.publishEvent(Events.java:98)
	at com.sun.faces.application.ApplicationImpl.publishEvent(ApplicationImpl.java:118)
	at com.sun.faces.application.ApplicationImpl.publishEvent(ApplicationImpl.java:110)
	at jakarta.faces.application.ApplicationWrapper.publishEvent(ApplicationWrapper.java:660)
	at com.sun.faces.lifecycle.Phase.queueException(Phase.java:123)
	at com.sun.faces.lifecycle.Phase.queueException(Phase.java:113)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:75)
	at com.sun.faces.lifecycle.RestoreViewPhase.doPhase(RestoreViewPhase.java:96)
	at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:131)
	at jakarta.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:691)
	at jakarta.faces.webapp.FacesServlet.service(FacesServlet.java:449)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:130)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:109)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:79)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:663)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1746)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1148)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
	at java.base/java.lang.Thread.run(Thread.java:1570)



-----------------------------------------------------------------------------------------------------------------------------------------------------



HTTP Status 500 – Internal Server Error

Type Exception Report

Message Ausdrucksfehler: Benanntes Objekt jakarta.faces.ViewRoot nicht gefunden.

Beschreibung The server encountered an unexpected condition that prevented it from fulfilling the request.

Exception

jakarta.servlet.ServletException: Ausdrucksfehler: Benanntes Objekt jakarta.faces.ViewRoot nicht gefunden.
	jakarta.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:698)
	jakarta.faces.webapp.FacesServlet.service(FacesServlet.java:449)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
	org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
	org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:663)
	org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382)
	org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905)
	org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1746)
	org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1148)
	org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
	java.base/java.lang.Thread.run(Thread.java:1570)

Root Cause

jakarta.faces.FacesException: Ausdrucksfehler: Benanntes Objekt jakarta.faces.ViewRoot nicht gefunden.
	com.sun.faces.util.Util.notNullNamedObject(Util.java:518)
	com.sun.faces.application.applicationimpl.InstanceFactory.createComponentApplyAnnotations(InstanceFactory.java:693)
	com.sun.faces.application.applicationimpl.InstanceFactory.createComponent(InstanceFactory.java:195)
	com.sun.faces.application.ApplicationImpl.createComponent(ApplicationImpl.java:415)
	jakarta.faces.application.ApplicationWrapper.createComponent(ApplicationWrapper.java:291)
	com.sun.faces.util.Util.getNamingContainerPrefix(Util.java:1254)
	com.sun.faces.context.RequestParameterMap.getNamingContainerPrefix(RequestParameterMap.java:86)
	com.sun.faces.context.RequestParameterMap.get(RequestParameterMap.java:56)
	com.sun.faces.context.RequestParameterMap.get(RequestParameterMap.java:33)
	java.base/java.util.Collections$UnmodifiableMap.get(Collections.java:1657)
	com.sun.faces.context.PartialViewContextImpl.isAjaxRequest(PartialViewContextImpl.java:112)
	com.sun.faces.context.AjaxNoAjaxExceptionHandler.getWrapped(AjaxNoAjaxExceptionHandler.java:35)
	jakarta.faces.context.ExceptionHandlerWrapper.isListenerForSource(ExceptionHandlerWrapper.java:108)
	com.sun.faces.application.applicationimpl.Events.processListeners(Events.java:236)
	com.sun.faces.application.applicationimpl.Events.invokeComponentListenersFor(Events.java:177)
	com.sun.faces.application.applicationimpl.Events.publishEvent(Events.java:98)
	com.sun.faces.application.ApplicationImpl.publishEvent(ApplicationImpl.java:118)
	com.sun.faces.application.ApplicationImpl.publishEvent(ApplicationImpl.java:110)
	jakarta.faces.application.ApplicationWrapper.publishEvent(ApplicationWrapper.java:660)
	com.sun.faces.lifecycle.Phase.queueException(Phase.java:123)
	com.sun.faces.lifecycle.Phase.queueException(Phase.java:113)
	com.sun.faces.lifecycle.Phase.doPhase(Phase.java:75)
	com.sun.faces.lifecycle.RestoreViewPhase.doPhase(RestoreViewPhase.java:96)
	com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:131)
	jakarta.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:691)
	jakarta.faces.webapp.FacesServlet.service(FacesServlet.java:449)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:483)
	org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
	org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:663)
	org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382)
	org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:905)
	org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1746)
	org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1148)
	org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63)
	java.base/java.lang.Thread.run(Thread.java:1570)
```

However, a deploy of example.war to Tomcat 10.1.x works like a charme. Maybe related: https://stackoverflow.com/questions/78117026/deployment-of-jsf-web-application-fails-on-tomcat-11-but-works-on-tomcat-10

Tested with Mojarra 4.0.7 (and Weld 5.1.3.Final). However, the same faulty behaviour with Mojarra 4.1.1 (and Weld 6.0.0.Beta4, even with Weld and JF XML namespaces updated to 4.1 and web.xml to 6.1).

Hopefully I did not miss something important for updating to Tomcat 11 :)

Many thanks for Mojarra and looking into the problem.

Chris

### PR DESCRIPTION
**Pull request by BalusC**
Fix #5511: don't anymore rely on CodeSource#getLocation(), instead obtain the URL of the resource itself via its own class loader

### CODE REVIEW

**Review by melloware — APPROVED** [review]

File: impl/src/main/java/com/sun/faces/config/manager/tasks/ProvideMetadataToAnnotationScanTask.java [hunk 1]
```diff
@@ -72,10 +74,12 @@ private void initializeIvars(Set<Class<?>> annotatedSet) {
                          * annotatedSet because the faces-config.xml that owns it has metadata-complete="true".
                          */
                         ArrayList<Class<?>> toRemove = new ArrayList<>(1);
-                        String sourceURIString = sourceURI.toString();
+                        String facesConfigURIString = facesConfigURI.toString();
                         if (annotatedSet != null) {
                             for (Class<?> clazz : annotatedSet) {
-                                if (sourceURIString.contains(clazz.getProtectionDomain().getCodeSource().getLocation().toString())) {
+                                String jarURIString = CURRENT_RESOURCE_IN_JAR_PATTERN.split(clazz.getResource(".").toString(), 2)[0];
```
Comment (mnriem) [inline impl/src/main/java/com/sun/faces/config/manager/tasks/ProvideMetadataToAnnotationScanTask.java:80]: Not seeing a test here that validates this change over?

**Review by mnriem — CHANGES_REQUESTED** [review]

File: impl/src/main/java/com/sun/faces/config/manager/tasks/ProvideMetadataToAnnotationScanTask.java (hunk 1 above)
Comment (BalusC) [reply impl/src/main/java/com/sun/faces/config/manager/tasks/ProvideMetadataToAnnotationScanTask.java]: Added integration test: https://github.com/eclipse-ee4j/mojarra/pull/5519/commits/1ff67143b9f9ab5dba14d1b8932a982b8dc47399
