### PR TITLE
Fix Response encoding not stored in the ext context session #5543

### LINKED ISSUE #5543: (4.0.x) Response encoding not stored in the ext context session (possible spec violation?)
**Describe the bug**

Since Mojarra 4.0.6 (probably after this PR https://github.com/eclipse-ee4j/mojarra/pull/5385), Mojarra doesn't store the response encoding into the external context session. Originally, this was performed by this line: https://github.com/eclipse-ee4j/mojarra/pull/5385/files#diff-b3a9aacd3be9aefe5ab7fe6e92c87862f999bff1c8523313a2c76451f5136422L1010

I think storing the session

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by BalusC**
#5543

### CODE REVIEW

File: impl/src/main/java/com/sun/faces/application/view/FaceletViewHandlingStrategy.java [hunk 1]
```diff
@@ -929,6 +929,11 @@ protected ResponseWriter createResponseWriter(FacesContext context) throws IOExc
         // Save encoding in UIViewRoot for faster consult when Util#getResponseEncoding() is invoked again elsewhere.
         context.getViewRoot().getAttributes().put(FACELETS_ENCODING_KEY, encoding);
 
+        // Save encoding in Session for consult in subsequent postback request as per spec section "2.5.2.2. Determining the Character Encoding".
```
Comment (mnriem) [inline impl/src/main/java/com/sun/faces/application/view/FaceletViewHandlingStrategy.java:932]: Why is this stored in the session?

Comment (jbaesner) [reply impl/src/main/java/com/sun/faces/application/view/FaceletViewHandlingStrategy.java:932]: As stated in that comment, this is mandated by the JSF 2.3 specification chapter 2.5.2.2 Determining the Character Encoding, see:

"[P1-start-encoding]At the end of the render-response phase, the ViewHandler must store the response character encoding
used by the underlying response object (e.g., the servlet or portlet response) in the session (if and only if a session
already exists) under a well known, implementation-dependent key."

Comment (mnriem) [reply impl/src/main/java/com/sun/faces/application/view/FaceletViewHandlingStrategy.java:932]: As I stated before this needs to be reviewed with the specified Servlet 6.0 specification in mind. I do not object to setting it, but I do not see any logic that looks at the Servlet level. Note that JSF 2.3 is not supported and I assume you meant to refer to Faces specifications?

Comment (jbaesner) [reply impl/src/main/java/com/sun/faces/application/view/FaceletViewHandlingStrategy.java:932]: Yes, my fault, sorry, I meant Faces 4.0...

Anyhow, the spec has not changed there, see [Jakarta Faces 4.0 specification](https://jakarta.ee/specifications/faces/4.0/jakarta-faces-4.0#determining-the-character-encoding).

As of that I don't see how this is related to the Servlet 6.0 specification, as the Faces specification already requires storing the character encoding in the session.

Comment (BalusC) [reply impl/src/main/java/com/sun/faces/application/view/FaceletViewHandlingStrategy.java:932]: > Why is this stored in the session?

Because last used form encoding is not sent back via headers/payload of a postback request per-se.

> Please review this with Servlet 6.0 specification, section 5.6. Internationalization in mind.

It's indeed used for `setRequestEncoding()` as mentioned in that spec to remedy any breakages.

**Comment by bmaxwell** [comment]
@arjantijms , is this one ok to merge? We have some users needing the fix.  Thanks !

**Comment by soul2zimate** [comment]
Hi @BalusC @arjantijms, Is there any plan to release a new 4.0.10 soon?
